include(InstallRequiredSystemLibraries)


set(CPACK_PACKAGE_CONTACT newacc@student.bmstu.ru)
set(CPACK_PACKAGE_VERSION_MAJOR ${PRINT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PRINT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PRINT_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION_TWEAK ${PRINT_VERSION_TWEAK})

set(CPACK_PACKAGE_VERSION ${PRINT_VERSION})

set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "static  solver library  ")


set(CPACK_RPM_PACKAGE_NAME "solver_library")
set(CPACK_RPM_PACKAGE_RELEASE 1)

set(CPACK_DEBIAN_PACKAGE_NAME "solver_lib_library")
set(CPACK_DEBIAN_PACKAGE_RELEASE 1)
include(CPack)
